### ISSUE TITLE
is it compatible with Glide ?

### ISSUE THREAD

**Issue by AngleV** [vinc3m1/RoundedImageView#122]

**Comment by hfahmy** [comment]
Yes it is except for this issue:

https://github.com/vinc3m1/RoundedImageView/issues/118#issue-101275097

**Comment by vinc3m1** [comment]
Thanks @hfahmy

**Comment by AngleV** [comment]
@vinc3m1 
Thanks
Any example how to use transformations with glide ?

**Comment by chitrang2008** [comment]
@AngleV 

Please follow below instructions to use transformations with glide :

1) Copy RoundedTransformationBuilder.java somewhere in your package.

2) Add below code in your RoundedTransformationBuilder.java file. Context is required by BitmapTransformation constructor.

    /**
     * Creates a {@link BitmapTransformation} for use with Glide.
     *
     * @return the {@link BitmapTransformation}
     */
    public BitmapTransformation build(Context context) {
        return new BitmapTransformation(context) {
            @Override
            protected Bitmap transform(BitmapPool pool, Bitmap toTransform, int outWidth, int outHeight) {
                Bitmap transformed = RoundedDrawable.fromBitmap(toTransform)
                        .setScaleType(mScaleType)
                        .setCornerRadius(mCornerRadii[0], mCornerRadii[1], mCornerRadii[2], mCornerRadii[3])
                        .setBorderWidth(mBorderWidth)
                        .setBorderColor(mBorderColor)
                        .setOval(mOval)
                        .toBitmap();
                if (!toTransform.equals(transformed)) {
                    toTransform.recycle();
                }
                return transformed;
            }

            @Override
            public String getId() {
            //                return getClass().getName();
                return "r:" + Arrays.toString(mCornerRadii)
                        + "b:" + mBorderWidth
                        + "c:" + mBorderColor
                        + "o:" + mOval;
            }
        };
    }

and you should import,

import com.bumptech.glide.load.engine.bitmap_recycle.BitmapPool;
import com.bumptech.glide.load.resource.bitmap.BitmapTransformation;
import com.makeramen.roundedimageview.Corner;
import com.makeramen.roundedimageview.RoundedDrawable;

3) Create Transformation by calling .build(context).

        Transformation transformation = new RoundedTransformationBuilder()
                .borderColor(Color.BLACK)
                .borderWidthDp(3)
                .cornerRadiusDp(30)
                .oval(false)
                .build(context);

4) And use .bitmapTransform(transformation) method of Glide.

        Glide.with(context)
                .load(url)
                .placeholder(R.drawable.img_placeholder)
                .error(R.drawable.img_placeholder)
                .bitmapTransform(transformation)
                .into(imageView);

@vinc3m1 Let me know if this is the correct way to do, so that I can contribute to this project to add support of Glide-Transformation.

**Comment by vinc3m1** [comment]
@chitrang2008 that looks pretty good, go ahead and open a PR and I can review.
