### ISSUE TITLE
Currently setting properties order does matters

### ISSUE THREAD

**Issue by cesards** [vinc3m1/RoundedImageView#6]
Hi Vince,

I've been playing a little bit more with the library. I've come to a strange thing,

I suppose before setting image bitmap or drawable, we should set all vars, but in your adapter (RoundedImageView demo) we can find:

<pre>
((RoundedImageView) view.findViewById(R.id.imageView1)).setImageBitmap(item.mBitmap);
            ((RoundedImageView) view.findViewById(R.id.imageView1)).setScaleType(item.mScaleType);

</pre>

which is very different, as we can see in the list:

<pre>
view.findViewById(R.id.imageView1)).setScaleType(item.mScaleType);
((RoundedImageView) view.findViewById(R.id.imageView1)).setImageBitmap(item.mBitmap);
            ((RoundedImageView) 
</pre>

I came to idea you want to use the first one, because, first you set the bitmap and after setting scale you do: invalidate();

but in the landing page you say:

<pre>
iv.setScaleType(ScaleType.CENTER_CROP);
iv.setCornerRadius(10);
iv.setBorderWidth(2);
iv.setBorderColor(Color.DKGRAY);
iv.setRoundedBackground(true);
iv.setImageDrawable(drawable);
iv.setBackground(backgroundDrawable);
</pre>

so you are setting vars first. Change the order of the sentences in your adapter, and see what happens in the listview, because imagens doesn't display well using the second code...

Thanks

**Comment by SpiritMan** [comment]
Binary XML file line #7: Error inflating class com.makeramen.rounded.RoundedImageView
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/item_warp"
    android:layout_width="match_parent"
    android:layout_height="54dp">

    <com.makeramen.roundedimageview.RoundedImageView xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/cart_goods_logo"
        android:layout_width="32dp"
        android:layout_height="32dp"
        android:layout_centerVertical="true"
        android:layout_marginLeft="@dimen/margin_eight_dp"
        android:src="@drawable/logo"
        app:riv_corner_radius="@dimen/radius"
        app:riv_oval="false" />

    <ImageView
        android:id="@+id/cart_label_icon"
        android:layout_width="24dp"
        android:layout_height="24dp"
        android:src="@drawable/atag_hot" />

**Comment by ruhanijeb** [comment]
@vinc3m1 

I am getting below error can you please help me its bit urgent.

UNHANDLED EXCEPTION:
[MonoDroid] Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class com.makeramen.roundedimageview.RoundedImageView ---> Android.Views.InflateException: Binary XML file line #1: Error inflating class com.makeramen.roundedimageview.RoundedImageView ---> Java.Lang.Reflect.InvocationTargetException: Exception of type 'Java.Lang.Reflect.InvocationTargetException' was thrown. ---> Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/makeramen/roundedimageview/R$styleable; ---> Java.Lang.ClassNotFoundException: Didn't find class "com.makeramen.roundedimageview.R$styleable" on path: DexPathList[[zip file "/data/app/com.dharm.roundview-O3fRH_QINgCJR69fIVU_bw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dharm.roundview-O3fRH_QINgCJR69fIVU_bw==/lib/x86, /system/fake-libs, /data/app/com.dharm.roundview-O3fRH_QINgCJR69fIVU_bw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[MonoDroid]    --- End of inner exception stack trace ---
[chatty] uid=10100(com.dharm.roundview) identical 2 lines
[MonoDroid]    --- End of inner exception stack trace ---
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <034d4a9852dd45bea9353cc7776c99f0>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <034d4a9852dd45bea9353cc7776c99f0>:0 
[MonoDroid]   at Android.App.Activity.SetContentView (System.Int32 layoutResID) [0x00022] in <a10f61e70eeb434e952fef884856c199>:0 
[MonoDroid]   at roundview.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00009] in /Users/dharmender/Projects/roundview/roundview/MainActivity.cs:25 
[MonoDroid]   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <a10f61e70eeb434e952fef884856c199>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.4(intptr,intptr,intptr)
[MonoDroid]   --- End of managed Android.Views.InflateException stack trace ---
[MonoDroid] android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class com.makeramen.roundedimageview.RoundedImageView
[MonoDroid] Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class com.makeramen.roundedimageview.RoundedImageView
[MonoDroid] Caused by: java.lang.reflect.InvocationTargetException
[MonoDroid] 	at java.lang.reflect.Constructor.newInstance0(Native Method)
[MonoDroid] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
[MonoDroid] 	at android.view.LayoutInflater.createView(LayoutInflater.java:647)
[MonoDroid] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
[MonoDroid] 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
[MonoDroid] 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
[MonoDroid] 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
[MonoDroid] 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
[MonoDroid] 	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:419)
[MonoDroid] 	at android.app.Activity.setContentView(Activity.java:2669)
[MonoDroid] 	at md5c083c2735bea61cb3dc6e6f7c0287fc9.MainActivity.n_onCreate(Native Method)
[MonoDroid] 	at md5c083c2735bea61cb3dc6e6f7c0287fc9.MainActivity.onCreate(MainActivity.java:29)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7009)
[MonoDroid] 	at android.app.Activity.performCreate(Activity.java:7000)
[MonoDroid] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
[MonoDroid] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
[MonoDroid] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
[MonoDroid] 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
[MonoDroid] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:164)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
[MonoDroid] Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/makeramen/roundedimageview/R$styleable;
[MonoDroid] 	at com.makeramen.roundedimageview.RoundedImageView.<init>(RoundedImageView.java:92)
[MonoDroid] 	at com.makeramen.roundedimageview.RoundedImageView.<init>(RoundedImageView.java:86)
[MonoDroid] 	... 27 more
[MonoDroid] Caused by: java.lang.ClassNotFoundException: Didn't find class "com.makeramen.roundedimageview.R$styleable" on path: DexPathList[[zip file "/data/app/com.dharm.roundview-O3fRH_QINgCJR69fIVU_bw==/base.apk"],nativeLibraryDirectories=[/data/app/com.dharm.roundview-O3fRH_QINgCJR69fIVU_bw==/lib/x86, /system/fake-libs, /data/app/com.dharm.roundview-O3fRH_QINgCJR69fIVU_bw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
[MonoDroid] 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[MonoDroid] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[MonoDroid] 	... 29 more
