### ISSUE TITLE
animated Drawables are unsupported

### ISSUE THREAD

**Issue by mcginty** [vinc3m1/RoundedImageView#86]
Animated drawables passed to `setImageDrawable` don't animate as expected, while they do in normal ImageViews. This goes for drawables like TransitionDrawable, as well as animated gifs (GifDrawable in https://github.com/koral--/android-gif-drawable).

Tested on a device with Android 4.4.4 and Android 5.0.2.

Example code:

```java
RoundedImageView imageView = (RoundedImageView) findViewById(R.id.wherever_it_is);
Drawable transition = new TransitionDrawable(new Drawable[]{new ColorDrawable(Color.TRANSPARENT), new ColorDrawable(Color.RED)});
imageView.setImageDrawable(transition);
transition.startTransition(500);
```

**Comment by vinc3m1** [comment]
I definitely can't support android-gif-drawable, adding transitive dependencies to other libraries is not an option. If there was a [`Transformation`](https://github.com/square/picasso/blob/master/picasso/src/main/java/com/squareup/picasso/Transformation.java) equivalent we could make a similar [`RoundedTransformationBuilder`](https://github.com/vinc3m1/RoundedImageView/blob/master/roundedimageview/src/main/java/com/makeramen/roundedimageview/RoundedTransformationBuilder.java) and I could support it as a `provided` dependency.

TransitionDrawables were always tricky to support well, so it's hard to say it'll ever have stable support since we can't predict what kind of drawables are inside a `TransitionDrawable` or any `LayerDrawable` for that matter.

I'm open to pull requests that improve TransitionDrawable compatibility, but in the meantime you probably need to manually merge the sources together and take what you need from each to get what you want.

**Comment by ando0689** [comment]
Hi. I use your lib and Picasso, but I cannot make the images transition to work. I wise this code, but it just loads without transformation. Can you help me?

		Transformation transformation = new RoundedTransformationBuilder()
				.oval(false)
				.build();

		final Uri photoUri =  Uri.parse(uriStr);

		Picasso.with (mContext)
				.load(photoUri)
				.fit()
				.placeholder(R.mipmap.ic_contact_picture)
				.transform(transformation)
				.into(img);
