### ISSUE TITLE
ImageView images are oval and not circular

### ISSUE THREAD

**Issue by markbroughton** [vinc3m1/RoundedImageView#92]
Probably user error but my images when loaded are coming back as oval and not circular as I want them. Problem seems not to be with xml but some where in my code.

XML:
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical"
    android:padding="4dip">
    <com.makeramen.roundedimageview.RoundedImageView
        android:id="@+id/user_image"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:src="@drawable/blank_image"
        android:scaleType="fitCenter"
        app:riv_border_width="2dip"
        app:riv_border_color="#009688"
        app:riv_mutate_background="true"
        app:riv_oval="true"
        android:layout_width="70dp"
        android:layout_height="70dp" />

Code:
   public class MyViewBinder implements SimpleCursorAdapter.ViewBinder {
        public boolean setViewValue(View view, Cursor cursor, int columnIndex) {

            if (view.getId() == R.id.image){
               image_string = cursor.getString(cursor.getColumnIndex("image"));
            }
            if (view.getId() == R.id.user_image) {
                RoundedImageView iv = (RoundedImageView) view;
                iv.setOval(true);
                Bitmap thumbnail;
                BitmapFactory.Options options = new BitmapFactory.Options();
                options.outHeight = 80;
                options.outWidth = 80;
                options.inSampleSize = 10;
                if (image_string.equals("")) {
                    thumbnail = (BitmapFactory.decodeResource(getResources(),R.drawable.blank_image,options));
                }else {

                    thumbnail = (BitmapFactory.decodeFile(image_string, options));
                }
                iv.setImageBitmap(thumbnail);
                return true;
            }

            return false;
        }
    }

Any help welcome
Thanks

**Comment by vinc3m1** [comment]
If you use a regular ImageView and it's a rectangle then it's a configuration error. If a regular ImageView is square and RoundedImageView is still oval then it's a bug. Feel free to re-open if it's the latter.

**Comment by cloudt** [comment]
Hi there. I'm also having this problem: I have multiple identical layouts in ListView items, displaying a ton of contacts differently: some circled, some elliptic. 

It seems the contacts added externally (which allow non-square ratios) are the ones that will look like an ellipsis rather than a circle. These layouts are XML-based. I have attempted using both scaleType="centerCrop" and "fitCenter", although I don't know if these have any effect on RoundedImageView either.

One minor detail: I am binding images to the view using [Nostra's Android Universal Image Loader](https://www.google.pt/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjojavQ-NvKAhUMaRQKHRkTAZsQFggeMAA&url=https%3A%2F%2Fgithub.com%2Fnostra13%2FAndroid-Universal-Image-Loader&usg=AFQjCNGgmKC8hBtbywLST53tMmNnUAuNQA&sig2=EABK9KX6Z4-IO_2lYXdU-w). The ImageScaleType (do not confuse with ImageView.Scaletype) I'm using is IN_SAMPLE_INT. I don't think this should have any effect as those don't change aspect ratio.

My view on the layout:
```
<com.makeramen.roundedimageview.RoundedImageView
            android:id="@+id/avatar"
            android:layout_width="@dimen/lists_message_photo_width"
            android:layout_height="@dimen/lists_message_photo_height"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:layout_centerVertical="true"
            android:layout_marginBottom="4.5dp"
            android:layout_marginTop="4.5dp"
            android:contentDescription="@string/avatar"
            android:src="@drawable/ic_placeholder_list"
            android:transitionName="@string/photo_transition"
            tools:src="@drawable/ic_contact_list_stroke_placeholder"
            android:scaleType="fitXY"
            app:riv_corner_radius="0dp"
            app:riv_border_width="0dp"
            app:riv_border_color="@android:color/holo_red_dark"
            app:riv_mutate_background="true"
            app:riv_oval="true"/>
```

And the binding call (analogous to setImageDrawable, just more efficient and with perks):
```
mOptions = new DisplayImageOptions.Builder()
                .showImageOnLoading(defaultDrawable)
                .showImageForEmptyUri(defaultDrawable)
                .showImageOnFail(defaultDrawable)
                .imageScaleType(ImageScaleType.IN_SAMPLE_INT)
                .cacheOnDisk(true)
                .cacheInMemory(true)
                .displayer(new FadeInBitmapDisplayer(300))
                .bitmapConfig(Bitmap.Config.RGB_565)
                .build();

ImageLoader.getInstance().displayImage(
                    contact.getUri().toString(),
                    holder.mContactImage, mOptions);
```

If you'd like I can add a screenshot of the issue.

**Comment by cloudt** [comment]
Apparently this is happening also without using the ImageLoader, with simple calls to setImageDrawable. But... I have hacked around the problem! It seems the XML-set scaletype is not "sticking" after programmatic calls to setImageDrawable, and the images fall back to "centerInside" (since the largest side [the large diameter in the ellipsis] ]will be totally contained inside the view, and the smaller one [the small diameter] won't fit the view)
